name: Simba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/SIMBA.png
    - assets/images/LOGO_INDOCEMENT.jpg
    - assets/images/icons/BOX.png
    - assets/images/icons/registered_assets.png
    - assets/images/icons/unscanned_assets.png

